# Generated by Django 5.0.4 on 2024-05-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='timezone',
            field=models.CharField(default='Asia/Calcutta', max_length=50),
        ),
    ]
