# Generated by Django 5.0.4 on 2024-05-03 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='requestdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
