# Generated by Django 5.0.4 on 2024-05-06 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service_request', '0003_rename_requestdate_servicerequest_requestdate_in_local_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicerequest',
            name='requestdate_in_utc',
        ),
    ]
