# Generated by Django 5.0.4 on 2024-05-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_request', '0005_alter_servicerequest_requestdate_in_local'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicerequest',
            name='requestdate_in_local',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
